# Zola configuration for hx documentation
# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://hx.raskell.io/docs"
title = "hx Documentation"
description = "Documentation for hx, the extremely fast Haskell package and project manager."
default_language = "en"
theme = "purple-haze"

# Compile Sass/SCSS
compile_sass = true

# Generate feed
generate_feeds = false

# Build options
build_search_index = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
smart_punctuation = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[slugify]
paths = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_javascript"

[extra]
# Theme mode
mode = "docs"

# Site metadata
author = "raskell.io"
github_repo = "https://github.com/raskell-io/hx"
product_url = "https://hx.raskell.io"

# SEO metadata
keywords = "haskell, package manager, documentation, hx, tutorial, guide"

# Social links
github = "https://github.com/raskell-io/hx"

# Documentation configuration
[extra.docs]
versioned = false
default_version = "latest"

# Navigation
[[extra.nav_links]]
name = "Home"
url = "https://hx.raskell.io"
external = true

[[extra.nav_links]]
name = "GitHub"
url = "https://github.com/raskell-io/hx"
external = true
